"""Configuration loading with ``${a.b}`` interpolation and path resolution.

Two layers (PLAN.md D16):

``config.yaml``        portable defaults, tracked in git. Must run on any machine.
``config.local.yaml``  this machine's facts, generated by setup, **gitignored**.

The local file deep-merges over the defaults, and interpolation runs *after* the merge so
that overriding ``disk.root`` also moves every ``${disk.root}/...`` path with it.

The split exists because the two files answer different questions. Defaults describe what
the project needs; the local file describes what this computer has — which disk is real,
how many GPUs there are, which model is downloaded. Shipping the second kind in a tracked
file is why a fresh clone used to fail before it reached anything useful: it pinned a
device node and a three-GPU layout that exist on exactly one machine.

Relative paths in the config resolve against the **config file's own directory**, not the
process working directory. ``./data`` therefore means the same thing however you invoke
``lara``, which a cwd-relative path would not.

Every filesystem path is resolved through ``realpath`` before use so a symlink cannot
silently redirect data onto a full disk. See ``lara.preflight``.
"""

from __future__ import annotations

import os
import re
from pathlib import Path
from typing import Any

import yaml

_INTERP = re.compile(r"\$\{([a-zA-Z0-9_.]+)\}")

REPO_ROOT = Path(__file__).resolve().parent.parent
DEFAULT_CONFIG = REPO_ROOT / "config.yaml"
LOCAL_CONFIG = REPO_ROOT / "config.local.yaml"


def deep_merge(base: dict[str, Any], over: dict[str, Any]) -> dict[str, Any]:
    """Recursively merge ``over`` into ``base``, returning a new dict.

    Dicts merge key by key; anything else replaces wholesale. Lists deliberately do **not**
    concatenate — ``forbid_paths: []`` in the local file has to be able to mean "nothing is
    forbidden here", and an appending merge could never express that.
    """
    out = dict(base)
    for k, v in (over or {}).items():
        if isinstance(v, dict) and isinstance(out.get(k), dict):
            out[k] = deep_merge(out[k], v)
        else:
            out[k] = v
    return out


def _lookup(tree: dict[str, Any], dotted: str) -> Any:
    node: Any = tree
    for part in dotted.split("."):
        if not isinstance(node, dict) or part not in node:
            raise KeyError(f"config interpolation ${{{dotted}}} does not resolve")
        node = node[part]
    return node


def _interpolate(node: Any, root: dict[str, Any], depth: int = 0) -> Any:
    if depth > 10:
        raise ValueError("config interpolation nested too deeply (cycle?)")
    if isinstance(node, dict):
        return {k: _interpolate(v, root, depth + 1) for k, v in node.items()}
    if isinstance(node, list):
        return [_interpolate(v, root, depth + 1) for v in node]
    if isinstance(node, str) and "${" in node:
        def sub(m: re.Match[str]) -> str:
            return str(_interpolate(_lookup(root, m.group(1)), root, depth + 1))

        return _INTERP.sub(sub, node)
    return node


class Config(dict):
    """Dict with dotted access, e.g. ``cfg.get_path("paths.metadata_db")``."""

    #: Files this config was assembled from, in application order. Set by :func:`load`.
    sources: list[Path] = []
    #: Directory relative paths resolve against — the base config file's own directory.
    base_dir: Path = REPO_ROOT

    def get_in(self, dotted: str, default: Any = None) -> Any:
        try:
            return _lookup(self, dotted)
        except KeyError:
            return default

    @property
    def has_local(self) -> bool:
        """Whether a machine-specific override file was found."""
        return any(p.name == LOCAL_CONFIG.name for p in self.sources)

    def get_path(self, dotted: str) -> Path:
        """Return a config path resolved through realpath (symlinks collapsed).

        Relative paths resolve against the config file's directory, so ``./data`` is
        stable regardless of where ``lara`` was invoked from.
        """
        raw = self.get_in(dotted)
        if raw is None:
            raise KeyError(f"no path configured at {dotted}")
        expanded = os.path.expanduser(str(raw))
        if not os.path.isabs(expanded):
            expanded = os.path.join(self.base_dir, expanded)
        return Path(os.path.realpath(expanded))

    def all_paths(self) -> dict[str, Path]:
        """Every configured path that will be written to, keyed by its config address."""
        out: dict[str, Path] = {"disk.root": self.get_path("disk.root")}
        for key in self.get_in("paths", {}) or {}:
            out[f"paths.{key}"] = self.get_path(f"paths.{key}")
        out["huggingface.home"] = self.get_path("huggingface.home")
        return out


def load(path: str | Path | None = None, *, local: bool = True) -> Config:
    """Load defaults, merge the machine-local overrides, then interpolate.

    Interpolation runs last, after the merge, so overriding ``disk.root`` in the local file
    carries every ``${disk.root}/...`` path along with it. Interpolating each layer
    separately would freeze the defaults' paths against the default root — the override
    would appear to apply while the data quietly went somewhere else.
    """
    p = Path(path) if path else DEFAULT_CONFIG
    with open(p) as fh:
        raw = yaml.safe_load(fh) or {}
    sources = [p]

    # An explicit --config selects that file alone. Layering a machine's overrides onto a
    # config the caller deliberately named would make the flag mean something other than
    # "use this configuration".
    if local and path is None and LOCAL_CONFIG.exists():
        with open(LOCAL_CONFIG) as fh:
            raw = deep_merge(raw, yaml.safe_load(fh) or {})
        sources.append(LOCAL_CONFIG)

    cfg = Config(_interpolate(raw, raw))
    cfg.sources = sources
    cfg.base_dir = p.resolve().parent
    return cfg
